# Generated by Django 3.0.3 on 2020-02-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apex_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='background',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='image_url',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='kills',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='map',
            name='map_url',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skin',
            name='image_url',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weapon',
            name='image_url',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weapontype',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
